export const BEERS = [
  {
    id: 'wit-and-wisdom',
    name: 'Wit & Wisdom',
    style: 'Belgian Witbier',
    accent: '#f5e6c8',
    glow: '#f0a830',
    tags: ['citrus', 'coriander', 'wheat'],
    description: 'Bright, zesty, and endlessly curious — like a conversation that never gets dull.',
    mood: 'sunny and curious',
    x: -6, z: -3,
  },
  {
    id: 'deep-ocean',
    name: 'Deep Ocean',
    style: 'Imperial Stout',
    accent: '#1a1a2e',
    glow: '#2d4a7a',
    tags: ['chocolate', 'espresso', 'molasses'],
    description: 'Dark, bottomless, and full of hidden currents. Not for the faint of palate.',
    mood: 'deep and brooding',
    x: 6, z: -3,
  },
  {
    id: 'arctic-dawn',
    name: 'Arctic Dawn',
    style: 'NEIPA',
    accent: '#ffd6a5',
    glow: '#ff8c42',
    tags: ['tropical', 'juicy', 'hazy'],
    description: 'First light breaking over frozen peaks — soft, warm, and impossibly vivid.',
    mood: 'optimistic glow',
    x: 0, z: -8,
  },
  {
    id: 'frost-bite',
    name: 'Frost Bite',
    style: 'Dry-hopped Pilsner',
    accent: '#a8d8ea',
    glow: '#55c5f5',
    tags: ['crisp', 'pine', 'clean'],
    description: 'The snap of cold air on your face when you open the tent flap at dawn. Clean. Awake.',
    mood: 'sharp and awake',
    x: -5, z: 5,
  },
  {
    id: 'tundra-blaze',
    name: 'Tundra Blaze',
    style: 'Smoked Amber',
    accent: '#c1694f',
    glow: '#e84a23',
    tags: ['campfire', 'smoke', 'caramel'],
    description: 'The warmth of a bonfire in the middle of nowhere. Smoke, amber light, stories.',
    mood: 'warm and smoky',
    x: 5, z: 5,
  },
  {
    id: 'polar-night',
    name: 'Polar Night',
    style: 'Barrel-aged Barleywine',
    accent: '#3d2c5e',
    glow: '#9b59b6',
    tags: ['plum', 'leather', 'vanilla'],
    description: 'Aged in the dark, slow to reveal its layers. Patient drinkers get the best rewards.',
    mood: 'mysterious and aged',
    x: 0, z: 0,
  },
]

export const COTTAGE_STYLES = {
  'wit-and-wisdom': {
    wallColor: '#c4955a', roofColor: '#8b5e3c', trimColor: '#f5e6c8',
    windowColor: '#f0a830', roofPitch: 0.9, width: 1.8, depth: 1.4, wallHeight: 0.9,
  },
  'deep-ocean': {
    wallColor: '#3a3a50', roofColor: '#2a2a3a', trimColor: '#4a5a7a',
    windowColor: '#2d4a7a', roofPitch: 1.2, width: 1.6, depth: 1.6, wallHeight: 0.8,
  },
  'arctic-dawn': {
    wallColor: '#d4a574', roofColor: '#c47530', trimColor: '#ffd6a5',
    windowColor: '#ff8c42', roofPitch: 1.0, width: 2.0, depth: 1.6, wallHeight: 1.0,
  },
  'frost-bite': {
    wallColor: '#b8c8d8', roofColor: '#7090a8', trimColor: '#d8eaf4',
    windowColor: '#55c5f5', roofPitch: 1.3, width: 1.6, depth: 1.4, wallHeight: 0.7,
  },
  'tundra-blaze': {
    wallColor: '#6b4a30', roofColor: '#4a2a18', trimColor: '#c1694f',
    windowColor: '#e84a23', roofPitch: 0.8, width: 2.2, depth: 1.8, wallHeight: 1.0,
  },
  'polar-night': {
    wallColor: '#4a3a5a', roofColor: '#3d2c5e', trimColor: '#6a5080',
    windowColor: '#9b59b6', roofPitch: 1.1, width: 1.8, depth: 1.6, wallHeight: 0.6,
  },
}
